# actualizar sistema operativo
#sudo apt update
#descargar python
# sudo apt install python3.10-pip -Y
# descargar pip
# sudo apt install 

FROM ubuntu:22.04
WORKDIR /ms1
COPY . .
RUN apt update
RUN apt install python3.10 -y
RUN apt install python3-pip -y
RUN pip3.10 install -r req.txt
EXPOSE 5555
CMD ["python3.10","app.py"]
